### ISSUE TITLE
Suggest: Don't reject suggestions containing an empty 'relevant-countries' entry

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/backend#24]
https://user-images.githubusercontent.com/4048809/103084953-376bdb80-45d8-11eb-8f15-52c29ba21f13.mp4

I have only checked this for 'relevant-countries'. It may also apply to other fields.

**Comment by aditya2712** [comment]
Hi @baltpeter I would like to take this issue

**Comment by zner0L** [comment]
@aditya2712 Go for it. @baltpeter if no relevant country is given we want it to be `'all'`, right?

**Comment by aditya2712** [comment]
Hi @zner0L , actually right now also, if no relevant country is given, then 'all' is being saved.

**Comment by baltpeter** [comment]
> if no relevant country is given we want it to be `'all'`, right?
 
Yep, that should already be implemented as @aditya2712 said.

This issue is for not rejecting the request if an "empty" country is in the list.

**Comment by aditya2712** [comment]
I have fixed the issue and created a PR for the same. Can you please review : [PR](https://github.com/datenanfragen/backend/pull/36) ?
