### ISSUE TITLE
Comments: trim message and author string

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/backend#34]
We should trim whitespace in the message and author field.

This is the relevant file:

https://github.com/datenanfragen/backend/blob/master/src/handlers/comments/putComment.js

**Comment by ikabir21** [comment]
I would like to work on this. Can you please assign this to me?

**Comment by baltpeter** [comment]
Sure! Thanks, @ikabir21.

**Comment by aditya2712** [comment]
Hi @baltpeter is this issue pending? I want to take this issue!!

**Comment by baltpeter** [comment]
@aditya2712 No, @ikabir21 is already assigned.
